#!/bin/python3

import math
import os
import random
import re
import sys

def rotate(a):
    new_a = [0]*len(a)
    for i in range(len(a)):
        pos = i-d
        while pos<0:
            pos += n
        new_a[pos] = a[i]
    print(' '.join(str(x) for x in new_a))

if __name__ == '__main__':
    nd = input().split()

    n = int(nd[0])

    d = int(nd[1])

    a = list(map(int, input().rstrip().split()))
    
    rotate(a)
