#!/bin/python3

import os
import sys

#
# Complete the primeCount function below.
#
def primeCount(n):
    count = 1
    factor = 2
    if n<=3: return n//2

    for i in range(3, n//2+1, 2):
        is_prime = True
        for j in range(3, i//2, 2):
            if i%j==0:
                is_prime = False
                break
        if is_prime: 
            factor*=i
            if factor>n: break
            else: count += 1
    return count

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        n = int(input())

        result = primeCount(n)

        fptr.write(str(result) + '\n')

    fptr.close()
