#!/bin/python3

import math
import os
import random
import re
import sys
from sklearn.linear_model import LinearRegression
import pandas as pd

data = pd.read_csv('trainingdata.txt', header=None)
data = data[data[1]<8]
X = data.iloc[:,0].values.reshape(-1,1)
y = data.iloc[:,-1]

model = LinearRegression().fit(X,y)
pred = model.predict(float(input()))
print(min(round(*pred,2),8.00))
