#!/bin/python3

import os
import sys

#
# Complete the equalStacks function below.
#
def equalStacks(h1, h2, h3):
    tot_h1 = sum(h1)
    tot_h2 = sum(h2)
    tot_h3 = sum(h3)
    while True:
        if tot_h1==tot_h2 and tot_h2==tot_h3:
            break
        high_stack = max(tot_h1, tot_h2, tot_h3)
        if high_stack == tot_h1:
            tot_h1 -= h1[0]
            h1.pop(0)
        elif high_stack == tot_h2:
            tot_h2 -= h2[0]
            h2.pop(0)
        else:
            tot_h3 -= h3[0]
            h3.pop(0)
    return tot_h1

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n1N2N3 = input().split()

    n1 = int(n1N2N3[0])

    n2 = int(n1N2N3[1])

    n3 = int(n1N2N3[2])

    h1 = list(map(int, input().rstrip().split()))

    h2 = list(map(int, input().rstrip().split()))

    h3 = list(map(int, input().rstrip().split()))

    result = equalStacks(h1, h2, h3)

    fptr.write(str(result) + '\n')

    fptr.close()
