#!/usr/bin/python

def displayPathtoPrincess(n,grid):
    if grid[0][0]=='p':
        print('UP\n'*(n//2)+'LEFT\n'*(n//2))
    elif grid[0][n-1]=='p':
        print('UP\n'*(n//2)+'RIGHT\n'*(n//2))
    elif grid[n-1][0]=='p':
        print('DOWN\n'*(n//2)+'LEFT\n'*(n//2))
    else:
        print('DOWN\n'*(n//2)+'RIGHT\n'*(n//2))

    
m = int(input())
grid = [] 
for i in range(0, m): 
    grid.append(input().strip())

displayPathtoPrincess(m,grid)
