#!/bin/python3

import math
import os
import random
import re
import sys

def isWeird(n):
    if n%2!=0:
        return 'Weird'
    else:
        if n<=5:
            return 'Not Weird'
        elif n<=20:
            return 'Weird'
        else:
            return 'Not Weird'

if __name__ == '__main__':
    N = int(input())

    result = isWeird(N)
    
    print(result)
