#!/bin/python3

import math
import os
import random
import re
import sys


if __name__ == '__main__':
    N = int(input())
    emails = []
    for N_itr in range(N):
        firstNameEmailID = input().split()

        firstName = firstNameEmailID[0]

        emailID = firstNameEmailID[1]

        if re.search('@gmail.com', emailID):
            emails.append([firstName,emailID])
    print(*[name[0] for name in sorted(emails, key= lambda x:x[0])], sep='\n')
