#!/bin/python3

import sys

n = int(input().strip())
a = list(map(int, input().strip().split(' ')))
# Write Your Code Here
swaps = 0
for i in range(n):
    temp = 0
    for j in range(n-1):
        if a[j]>a[j+1]:
            t = a[j]
            a[j] = a[j+1]
            a[j+1] = t
            swaps += 1
            temp += 1
    if temp == 0:
        break
print('Array is sorted in %i swaps.' %(swaps))
print('First Element: %i' %(a[0]))
print('Last Element: %i' %(a[-1]))
