#!/bin/python3

import math
import os
import random
import re
import sys

def hourglass(arr):
    sums = []
    for i in range (1,len(arr)-1):
        for j in range(1, len(arr)-1):
            sums.append(arr[i-1][j-1]+arr[i-1][j]+arr[i-1][j+1]+arr[i][j]+arr[i+1][j-1]+arr[i+1][j]+arr[i+1][j+1])
    return max(sums)

if __name__ == '__main__':
    arr = []

    for _ in range(6):
        arr.append(list(map(int, input().rstrip().split())))

    print((hourglass(arr)))
